"""Adapter for the real SynCAN dataset (ETAS/Bosch), distributed as a nested
zip: one master zip containing train_1.zip..train_4.zip and six test_*.zip
files, each of which contains exactly one CSV.

Normalizes the real files' schema to the canonical one data/loader.py and
everything downstream (registry, grid alignment, ...) already expects:

- **Column names**: the real CSV header is
  `Label,Time,ID,Signal1,Signal2,Signal3,Signal4` -- the SynCAN README
  documents `Signal1_of_ID`..`Signal4_of_ID`, but the files actually shipped
  in the zip omit that suffix. Renamed here, once, at the boundary, so
  nothing downstream needs to know real data ever looked different from the
  synthetic generator's output.
- **Time units**: the real files record Time in milliseconds (confirmed by
  inspecting train_1.csv: consecutive same-ID gaps of exactly 15/30/45,
  matching the README's per-ID periods in ms). Every other module in this
  pipeline (`config.GRID_STEP_SECONDS`, attack-window timestamps, ...)
  assumes seconds, so Time is divided by 1000 here.
- **Row/column order**: matched to `data/loader.py.REQUIRED_COLUMNS`.

The real dataset has no "fuzzing" test set -- claude.md's six attack types
include fuzzing, but SynCAN's own six published files are test_normal
(clean), test_plateau, test_continuous (= claude.md's "drift"),
test_playback (= "replay"), test_suppress (= "suppression"), and
test_flooding. TEST_FILES below only maps the five real attack types (plus
"normal"); fuzzing stays synthetic-only, generated by data/synthetic.py.

Reading straight out of the nested zip (no intermediate extraction to disk)
works but is slow to repeat -- zipfile still has to decompress every byte up
to `nrows`, and the master zip's train members alone are ~70MB compressed /
~350MB each uncompressed. scripts/prepare_syncan_data.py materializes the
normalized CSVs to data/raw/ once, so everything else (loader.py,
run_detector.py) just opens a plain file afterward like it does for the
synthetic dataset.
"""

from __future__ import annotations

import io
import zipfile
from pathlib import Path

import pandas as pd

from canids.data.loader import REQUIRED_COLUMNS

RAW_SIGNAL_COLUMNS = ["Signal1", "Signal2", "Signal3", "Signal4"]
CANONICAL_SIGNAL_COLUMNS = ["Signal1_of_ID", "Signal2_of_ID", "Signal3_of_ID", "Signal4_of_ID"]

TRAIN_FILES = ["train_1", "train_2", "train_3", "train_4"]

# claude.md attack-type name -> SynCAN's own inner file stem.
TEST_FILES = {
    "normal": "test_normal",
    "plateau": "test_plateau",
    "drift": "test_continuous",
    "replay": "test_playback",
    "suppression": "test_suppress",
    "flooding": "test_flooding",
}


def _read_inner_csv(master_zip: Path, inner_stem: str, nrows: int | None = None) -> pd.DataFrame:
    """Read `<inner_stem>.csv` out of `<inner_stem>.zip` inside the master
    zip, without extracting either zip to disk. `nrows` is passed straight
    to pandas, which stops reading (and zipfile stops decompressing) as soon
    as enough rows have been parsed -- it genuinely limits work done, not
    just what's kept, so a small `nrows` makes this fast even against the
    ~350MB train members.
    """
    with zipfile.ZipFile(master_zip) as master:
        matches = [n for n in master.namelist() if n.endswith(f"{inner_stem}.zip")]
        if len(matches) != 1:
            raise ValueError(f"expected exactly one member ending in {inner_stem}.zip in {master_zip}, found {matches}")
        inner_bytes = master.read(matches[0])
    with zipfile.ZipFile(io.BytesIO(inner_bytes)) as inner:
        csv_matches = [n for n in inner.namelist() if n.endswith(f"{inner_stem}.csv")]
        if len(csv_matches) != 1:
            raise ValueError(f"expected exactly one member ending in {inner_stem}.csv inside {matches[0]}, found {csv_matches}")
        with inner.open(csv_matches[0]) as f:
            return pd.read_csv(f, nrows=nrows)


def normalize(df: pd.DataFrame) -> pd.DataFrame:
    """Rename/reorder/convert one real-schema SynCAN DataFrame to the
    canonical schema data/loader.py expects. Safe to call on an
    already-canonical DataFrame's copy only if its columns still include the
    raw Signal1..4 names -- this is meant for real SynCAN data, not for
    re-normalizing synthetic output.
    """
    df = df.rename(columns=dict(zip(RAW_SIGNAL_COLUMNS, CANONICAL_SIGNAL_COLUMNS)))
    df["ID"] = df["ID"].astype(str)
    df["Time"] = df["Time"] / 1000.0
    return df[REQUIRED_COLUMNS].sort_values("Time").reset_index(drop=True)


def load_syncan_csv(master_zip: Path, inner_stem: str, nrows: int | None = None) -> pd.DataFrame:
    """Read and normalize one real SynCAN member straight out of the nested
    zip -- e.g. inner_stem="train_1" or inner_stem="test_playback".
    """
    return normalize(_read_inner_csv(Path(master_zip), inner_stem, nrows=nrows))


def concatenate_with_time_offset(dfs: list[pd.DataFrame], gap_seconds: float) -> pd.DataFrame:
    """Concatenate independently-recorded sessions (each with its own Time
    starting near 0) into one continuous timeline: the SynCAN README
    recommends concatenating all four training files into the full training
    set, but their raw Time columns overlap (each session starts near t=0),
    so a naive concat-and-sort-by-Time would interleave unrelated sessions'
    rows instead of laying them end to end.

    Each subsequent DataFrame's Time is shifted to start `gap_seconds` after
    the previous one's last tick. This creates one artificial discontinuity
    per seam -- a handful of forecast windows spanning a seam will see a
    nonsensical jump -- negligible among the millions of genuine windows a
    concatenated file this size produces, and the standard way multi-session
    logs get joined for a single sequence model.
    """
    parts = []
    offset = 0.0
    for df in dfs:
        shifted = df.copy()
        shifted["Time"] = shifted["Time"] + offset
        parts.append(shifted)
        offset = shifted["Time"].max() + gap_seconds
    return pd.concat(parts, ignore_index=True).sort_values("Time").reset_index(drop=True)
