"""CLI entry point: train Branch 1 (GRU forecaster) on a normal CSV,
calibrate thresholds + build the correlation graph from it, then run
detection + attribution on a test CSV and print detailed, per-signal flags
for a handful of example ticks.

This wires together everything built so far (Steps 1-9: registry, grid
alignment, staleness, windowing, correlation graph, GRU baseline, naive
confidence gating, threshold calibration, attribution rules) into one
runnable pipeline, for manual inspection of what the model + attribution
layer actually predict on a given sequence -- one sequence at a time, in
detail. It is deliberately NOT a replacement for Step 13
(canids.evaluate / scripts/run_evaluation.py), which reports real
per-attack-type precision/recall/F1, a rule-collision confusion matrix, and
a threshold-sensitivity sweep across every attack type at once -- see
docs/09-evaluation.md. This script's "quick tally" section is a rough,
single-run sanity check for whatever one CSV you pointed it at, not a
reported metric; use run_evaluation.py for the aggregate picture. There is
also still no Isolation Forest (Branch 2, Step 11) or fusion (Step 12)
anywhere -- the verdict printed here is Branch 1 + attribution only.

Usage (from the repo root, with the canids environment active):
    python scripts/run_detector.py
    python scripts/run_detector.py --attack-type replay --limit 3
    python scripts/run_detector.py --test-csv path/to/other.csv --index 4200

Defaults point at the synthetic placeholder dataset (data/synthetic/,
generated by scripts/generate_synthetic_data.py). To run against the real
SynCAN dataset instead, first materialize normalized CSVs with
scripts/prepare_syncan_data.py (it converts the real files' schema and
millisecond timestamps to the canonical format -- see canids.data.syncan),
then point --normal-csv/--test-csv at its output, e.g.:
    python scripts/prepare_syncan_data.py
    python scripts/run_detector.py \
        --normal-csv data/raw/syncan_train_1.csv \
        --test-csv data/raw/syncan_test_replay.csv
No other code changes are needed -- registry.build_registry and
data/loader.py are schema-generic once the CSV is in canonical form.

Training uses models.gru_seq2seq.train_streaming, which gathers each batch
on demand from the joint vector instead of pre-building the full windowed
(X, y) tensor -- see docs/notes-real-data-scaling.md for why that
materialization step is a real memory blocker at real SynCAN's scale (tens
of GB for one training file) and not worth paying even on the small
synthetic dataset. --batch-size defaults to 256 and --early-stopping-patience
to 5 (0 disables it, running the full --epochs) -- both per that doc's
measured recommendations.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from canids.attribution.rules import attribute
from canids.calibration import calibrate
from canids.config import (
    DEFAULT_CALIBRATION_PERCENTILE,
    GRID_STEP_SECONDS,
    RANDOM_SEED,
    SEQUENCE_LENGTH,
    SYNTHETIC_DATA_DIR,
    TRAINING_EPOCHS,
)
from canids.correlation import build_correlation_graph
from canids.data.grid import align_to_grid
from canids.data.loader import load_attack, load_normal, split_train_val
from canids.data.staleness import compute_staleness
from canids.data.windowing import build_joint_vector, valid_forecast_ticks
from canids.evaluate import resolve_ground_truth
from canids.models import naive
from canids.models.gru_seq2seq import GRUForecaster, predict_streaming, train_streaming
from canids.registry import build_registry

ATTACK_TYPES = ["replay", "plateau", "drift", "suppression", "flooding", "fuzzing"]


def _print_header(title: str) -> None:
    print()
    print(title)
    print("-" * len(title))


def _fmt(x: float) -> str:
    return f"{x:.4f}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--normal-csv", type=Path, default=SYNTHETIC_DATA_DIR / "normal.csv")
    parser.add_argument("--test-csv", type=Path, default=None, help="defaults to --attack-type's synthetic CSV")
    parser.add_argument("--attack-type", choices=ATTACK_TYPES, default="replay")
    parser.add_argument("--sequence-length", type=int, default=SEQUENCE_LENGTH)
    parser.add_argument("--epochs", type=int, default=TRAINING_EPOCHS, help="maximum epochs; early stopping (see below) usually stops sooner")
    parser.add_argument(
        "--batch-size",
        type=int,
        default=256,
        help="training/eval batch size. 256 measurably beats the config default of 64 on this workload (see docs/notes-real-data-scaling.md); raise further (e.g. 1024) on larger real-data runs.",
    )
    parser.add_argument(
        "--early-stopping-patience",
        type=int,
        default=5,
        help="stop once validation loss hasn't improved for this many epochs (0 disables early stopping, always running the full --epochs).",
    )
    parser.add_argument("--percentile", type=float, default=DEFAULT_CALIBRATION_PERCENTILE)
    parser.add_argument("--val-fraction", type=float, default=0.2)
    parser.add_argument("--seed", type=int, default=RANDOM_SEED)
    parser.add_argument("--index", type=int, default=None, help="raw tick index in the test CSV's grid to inspect")
    parser.add_argument("--limit", type=int, default=5, help="how many example ticks to print in detail")
    parser.add_argument(
        "--grid-step",
        type=float,
        default=GRID_STEP_SECONDS,
        help=(
            "grid tick spacing in seconds (default from config.GRID_STEP_SECONDS). Real SynCAN's fastest "
            "signals repeat every ~15ms, so the 10ms default still resolves them without change; override "
            "if you point this at data with a different cadence."
        ),
    )
    args = parser.parse_args()

    test_csv = args.test_csv or (SYNTHETIC_DATA_DIR / f"attack_{args.attack_type}.csv")
    grid_step = args.grid_step
    early_stopping_patience = args.early_stopping_patience if args.early_stopping_patience > 0 else None

    _print_header("Dataset")
    print(f"normal (train/val): {args.normal_csv}")
    print(f"test:                {test_csv}")

    registry = build_registry([args.normal_csv])
    print(f"registry: {registry.n_signals} signals, vector_size={registry.vector_size}")
    for entry in registry.entries:
        print(f"  [{entry.signal_index:2d}] {entry.name}  (value@{entry.value_index}, staleness@{entry.staleness_index})")

    normal_df = load_normal(args.normal_csv)
    train_df, val_df = split_train_val(normal_df, val_fraction=args.val_fraction)
    train_alignment = align_to_grid(train_df, registry, step=grid_step)
    val_alignment = align_to_grid(val_df, registry, step=grid_step)
    train_joint = build_joint_vector(train_alignment, registry)
    val_joint = build_joint_vector(val_alignment, registry)
    val_ticks = valid_forecast_ticks(val_joint, sequence_length=args.sequence_length)

    _print_header("Training (GRU baseline, Branch 1)")
    n_train_windows = len(valid_forecast_ticks(train_joint, sequence_length=args.sequence_length))
    print(
        f"train windows: {n_train_windows}, val windows: {len(val_ticks)}, sequence_length={args.sequence_length}, "
        f"batch_size={args.batch_size}, max_epochs={args.epochs}, early_stopping_patience={early_stopping_patience}"
    )
    print("(batches gathered on demand from the joint vector -- see docs/notes-real-data-scaling.md's streaming fix)")
    model = GRUForecaster(vector_size=registry.vector_size, n_signals=registry.n_signals)
    history = train_streaming(
        model, registry, train_joint, val_joint,
        sequence_length=args.sequence_length, epochs=args.epochs, batch_size=args.batch_size,
        seed=args.seed, early_stopping_patience=early_stopping_patience,
    )
    print(
        f"ran {len(history.train_loss)}/{args.epochs} epochs -- "
        f"final train_loss={history.train_loss[-1]:.5f}  val_loss={history.val_loss[-1]:.5f}"
    )

    y_val, pred_val = predict_streaming(model, registry, val_joint, val_ticks, args.sequence_length, args.batch_size)
    val_residuals = y_val - pred_val
    naive_val_residuals = naive.residuals_streaming(val_joint, registry, val_ticks)
    confidence_mask = naive.confidence_gate(val_residuals, naive_val_residuals)
    confidence_weight = naive.confidence_weight(val_residuals, naive_val_residuals)

    _print_header("Per-signal confidence gate (GRU vs. naive persistence on validation data)")
    for entry in registry.entries:
        j = entry.signal_index
        trust = "trustworthy" if confidence_mask[j] else "LOW CONFIDENCE (residual-based rules suppressed)"
        print(f"  {entry.name:12s} model_var={np.var(val_residuals[:, j]):.5f}  naive_var={np.var(naive_val_residuals[:, j]):.5f}  -> {trust}")

    val_staleness = compute_staleness(val_alignment)
    calibration = calibrate(
        val_residuals, val_alignment.values, val_staleness, val_alignment.updated, registry, percentile=args.percentile
    )

    _print_header(f"Calibration (percentile={args.percentile})")
    for entry in registry.entries:
        j = entry.signal_index
        print(
            f"  {entry.name:12s} residual_thr={_fmt(calibration.residual_thresholds[j])}  "
            f"staleness_thr={_fmt(calibration.staleness_thresholds[j])}  "
            f"cusum_k={_fmt(calibration.cusum_k[j])}  cusum_thr={_fmt(calibration.cusum_thresholds[j])}"
        )

    full_normal_alignment = align_to_grid(normal_df, registry, step=grid_step)
    full_normal_joint = build_joint_vector(full_normal_alignment, registry)
    correlation = build_correlation_graph(full_normal_joint, registry)

    _print_header(f"Correlation graph ({len(correlation.edges)} edges, {correlation.n_folds}-fold stable)")
    if not correlation.edges:
        print("  (no stable partner edges found)")
    for edge in correlation.edges:
        a = registry.entries[edge.signal_a].name
        b = registry.entries[edge.signal_b].name
        print(f"  {a} <-> {b}   strength={_fmt(edge.strength)}  fold_agreement={edge.fold_agreement}/{correlation.n_folds}")

    _print_header("Running detection on test data")
    test_df = load_attack(test_csv)
    test_alignment = align_to_grid(test_df, registry, step=grid_step)
    test_joint = build_joint_vector(test_alignment, registry)
    test_staleness_full = compute_staleness(test_alignment)

    tick_indices = valid_forecast_ticks(test_joint, sequence_length=args.sequence_length)
    if len(tick_indices) == 0:
        print("test CSV too short for the chosen sequence length -- nothing to detect.")
        return
    y_test, pred_test = predict_streaming(model, registry, test_joint, tick_indices, args.sequence_length, args.batch_size)
    residuals_test = y_test - pred_test
    values_at_ticks = test_alignment.values[tick_indices]
    staleness_at_ticks = test_staleness_full[tick_indices]

    result = attribute(
        residuals_test, values_at_ticks, staleness_at_ticks, calibration, correlation, registry,
        confidence_mask=confidence_mask,
        confidence_weight=confidence_weight,
    )
    detector_flag = np.array([any(label is not None for label in row) for row in result.primary_label])
    gt_full, gt_source = resolve_ground_truth(test_csv, test_df, test_alignment.times, grid_step)
    gt_at_ticks = gt_full[tick_indices]

    _print_header("Quick tally (informal -- see Step 13 for a real evaluation)")
    print(f"ground truth source: {gt_source}")
    print(f"ticks evaluated: {len(tick_indices)}")
    print(f"ground-truth attack ticks: {int(gt_at_ticks.sum())}")
    print(f"detector-flagged ticks (any signal's primary_label set): {int(detector_flag.sum())}")
    print(f"  overlap (flagged AND ground-truth):     {int((detector_flag & gt_at_ticks).sum())}")
    print(f"  flagged but no ground-truth label:      {int((detector_flag & ~gt_at_ticks).sum())}")
    print(f"  ground-truth but not flagged:            {int((~detector_flag & gt_at_ticks).sum())}")
    print(
        f"rule firings (signal-tick pairs): suppression={int(result.suppression_fired.sum())}  "
        f"plateau={int(result.plateau_fired.sum())}  drift={int(result.drift_fired.sum())}  "
        f"replay={int(result.replay_fired.sum())}"
    )

    if args.index is not None:
        positions = np.where(tick_indices == args.index)[0]
        if len(positions) == 0:
            print(
                f"\ntick {args.index} isn't available for inspection (inside the warm-up region, "
                f"or outside the range {tick_indices.min()}..{tick_indices.max()}); nothing to show."
            )
            return
        selected = [int(positions[0])]
        selection_note = f"tick {args.index} (as requested)"
    else:
        attack_positions = np.where(gt_at_ticks)[0]
        if len(attack_positions) > 0:
            selected = attack_positions[: args.limit].tolist()
            selection_note = "first ground-truth attack ticks"
        elif detector_flag.any():
            selected = np.where(detector_flag)[0][: args.limit].tolist()
            selection_note = "first detector-flagged ticks (no ground-truth Label found)"
        else:
            selected = list(range(min(args.limit, len(tick_indices))))
            selection_note = "first available ticks (nothing flagged or labeled)"

    _print_header(f"Detailed per-tick output ({selection_note})")
    for pos in selected:
        tick = int(tick_indices[pos])
        time = float(test_alignment.times[tick])
        overall = "ATTACK" if detector_flag[pos] else "NORMAL"
        gt = "attack-labeled" if gt_at_ticks[pos] else "normal-labeled"
        print(f"\n=== tick {tick}  t={time:.4f}s  ground-truth: {gt}  detector verdict: {overall} ===")
        header = f"  {'signal':12s} {'predicted':>10s} {'actual':>10s} {'residual':>10s} {'staleness':>9s}  rules fired -> primary"
        print(header)
        for entry in registry.entries:
            j = entry.signal_index
            fired = result.fired_rules(pos, j)
            primary = result.primary_label[pos, j] or "-"
            fired_str = ",".join(fired) if fired else "-"
            print(
                f"  {entry.name:12s} {_fmt(pred_test[pos, j]):>10s} {_fmt(y_test[pos, j]):>10s} "
                f"{_fmt(residuals_test[pos, j]):>10s} {staleness_at_ticks[pos, j]:>9.0f}  {fired_str} -> {primary}"
            )


if __name__ == "__main__":
    main()
